easy_admin:
    entities:
        - App\Entity\User
        - App\Entity\Artist
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
