fos_rest:
    view:
        formats:
            jsonp: true
            json: true
            rss: false
            xml: false
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        include_format:       false
