jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'

    handlers:
        datetime:
            default_format: "Y-m-d\\TH:i:sP" # ATOM

    property_naming:
#        id: ~
        separator:  _
        lower_case: true
        enable_cache: true
