nelmio_api_doc:
    routes:
        path_patterns: # an array of regexps
            - ^/api
    documentation:
        info:
            title: 'SouSound'
            description: 'Sound manager platform.'
            version: 0.1.0
