#! /bin/sh

php bin/console cache:warmup \
    && php bin/console doctrine:database:drop --force \
    ; php bin/console doctrine:database:create \
    ; php bin/console doctrine:schema:validate --skip-sync \
    && php bin/console doctrine:schema:update --dump-sql \
    && php bin/console doctrine:schema:update --force \
    && php bin/console doctrine:schema:validate \
    && php bin/console doctrine:fixtures:load --no-interaction -vvv
