easy_admin:
    entities:
        Album:
            class: 'App\Entity\Album'
            label: 'Albums'
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'firstName' }
                    - { property: 'lastName' }
                    - { property: 'email' }
                    - { property: 'lastLogin' }
            form:
                fields:
                    - { property: 'firstName' }
                    - { property: 'lastName' }
                    - { property: 'email' }
                    - { property: 'plainPassword' }
