easy_admin:
    site_name: 'SouSound'
    formats:
        date: 'm/d/Y'
        datetime: 'm/d/Y H:i:s'
    design:
        color_scheme: 'dark'
        brand_color: '#8b0000'
        form_theme:
            - 'horizontal'
        menu:
            - { label: 'Users' }
            - 'DownloadUtil'
            - 'Playlist'
            - 'User'
            - { label: 'Sounds' }
            - 'Track'
            - 'Artist'
            - 'Album'
            - 'Label'
    list:
        actions:
            - { name: 'show', icon: 'search', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: '-delete' }
